# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-27 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.TextField()),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('city', models.TextField()),
                ('sex', models.TextField()),
                ('date_of_birth', models.TextField()),
            ],
        ),
    ]
